services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-nest-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mauricio123
      - POSTGRES_DB=bait_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
